in-cluster/default.yaml

We want to trigger an advised workaround once a known Weave error has been found. The originating public facing issue for this is: https://github.com/weaveworks/weave/blob/master/site/tasks/ipam/troubleshooting-ipam.md?rgh-link-date=2022-03-04T18%3A34%3A26Z#seeded-by-different-peers.
By adding a text analyzer that checks if the error `IP Allocation was seeded by different peers` is present, We can immediately offer a workaround to resolve the issue for the user.

Update default.yaml - Add Weave analyzer

---

host/resource-contention.yaml

```
3.4G    /var/lib/kurl/assets
1.3G    /var/lib/kurl/assets/rook-1.5.9.tar.gz
1.1G    /var/log/apiserver
897M    /var/lib/kurl/assets/kubernetes-1.19.16.tar.gz
812M    /var/lib/kurl/assets/docker-20.10.5.tar.gz
723M    /var/lib/snapd/snaps
683M    /usr/bin
...
```

get a report of large files and dirs from host

---

host/cluster-down.yaml

I don't think 24 hours is enough time - sometimes we get a case, and it might be 24 hours before we get a response from "please run this host collector" and the important time window may have passed.  I might even prefer not using `--since` option at all and defaulting to collecting everything present in journald at the time.  But 7 might be a good compromise

increase journalctl collection to 7 days

---

host/cluster-down.yaml

A fair few times when we get a cluster-down support-bundle there are messages about the apiserver not responding. it would be nice to confirm:
1. what port the apiserver is listening on
2. if it's listening at all
without having to ask for another support bundle or manual commands.

Add netstat port list to cluster-down spec

---

.gitignore
host/cluster-down.yaml

Fix the endpoint that should be used. 
Also, improved the message to let us know what check was done. 
See:
Partial fix to: https://github.com/replicatedhq/troubleshoot-specs/issues/34

fix: curl k8s api

---

host/cluster-down.yaml

Fix the etcd health check. See:
PS.: collected the result might be helpful when it is not health since we will be able to check the reason. 
- Closes: https://github.com/replicatedhq/troubleshoot-specs/issues/14
- Closes: https://github.com/replicatedhq/troubleshoot-specs/issues/34

fix etcd health check

---

in-cluster/no-exec.yaml

`rook-ceph` cluster contains only rook/ceph pods. No need to filter by labels.

Collect all logs from rook-ceph pods

---

in-cluster/default-kurl.yaml
in-cluster/default.yaml

For cases where a user hosts their application behind contour, collected logs would help diagnose problems.

Collect contour pod logs

---

in-cluster/default-kurl.yaml

Add check for know issue scenario to share the community topic with the workaround: https://community.replicated.com/t/managing-nodes-when-the-previous-rook-version-is-in-use-might-leave-ceph-in-an-unhealthy-state-where-mon-pods-are-not-rescheduled/1099
Related to: [sc-57227]

add check for know issue scenario

---

in-cluster/default-kurl.yaml
in-cluster/default.yaml

Health check collector and analyser to ensure https://replicated.app is healthy.
Fixes: https://github.com/replicatedhq/troubleshoot-specs/issues/59

Health check replicated.app

---

host/default.yaml

When network related problems occur, we need all the information we can get at hand. Collect `flannel` and `kube-proxy` logs from the host

Collect logs for kube-proxy and flannel from host

---

in-cluster/default.yaml

Fixes: #43 
**Analysis without errors**
[support-bundle.tar.gz](https://github.com/replicatedhq/troubleshoot-specs/files/11982995/support-bundle.tar.gz)
```sh
[evans] $ analyze support-bundle.tar.gz --analyzers=in-cluster/default.yaml
...
Pass: Weave IP Allocation
Weave is ready, there are no IP allocation issues.
...
```
**Analysis with errors**
[support-bundle-with-error.tar.gz](https://github.com/replicatedhq/troubleshoot-specs/files/11983837/support-bundle-with-error.tar.gz)
```sh
[evans] $ analyze support-bundle-with-error.tar.gz --analyzers=in-cluster/default.yaml
...
Fail: Weave IP Allocation
IP Allocation issues detected. Please run `rm /var/lib/weave/weave-netdata.db && reboot` on each node to resolve this.
...
```

fix: Correctly detect weave IP allocation issues

---

host/default.yaml

Analyser to check of localhost resolves to `127.0.0.1`
Fixes: #56

chore: resolve localhost host collector and analyser

---

host/default.yaml

This should help see what nameservers are used to resolve DNS queries inside a cluster

Collect /etc/resolv.conf inside a pod

---

host/default.yaml

Not all systems will have 'netstat' which the current default host collector spec uses to collect the route table information

chore: Collect route table using 'ip route' command

---

host/default.yaml

Analyser to check if SELinux is enabled in a system. kURL installer disables it during installation but it would be good to know if it got reenabled after installation e.g by some security tooling/automation or a sysadmin

Analyser to check if SELinux is exabled

---

in-cluster/default.yaml

* For add-ons that are not always installed, we want to use `ignoreIfNoFiles=true` so as not to warn of the files are not found
* Use the deployment manifest to extract the installed version of `ekco`

Fixes to analysers causing some false warning

---

host/default.yaml

`xagt` has a nasty habit of locking iptables and preventing kube-proxy from injecting it's rules.

 Add fireeye xagt to list of security tools

---

in-cluster/default.yaml

Related to: https://app.shortcut.com/replicated/story/107874/pvc-filling-up-need-a-collector-analyzer
Demo: https://asciinema.org/a/R2FDTfEg53wobhTxA6KkEku5m

Add PVC check in default spec

---

in-cluster/default.yaml

This is how analysis would look like:

Added event-analyzer

---

in-cluster/default.yaml

As previously it was difficult to find out which collector task is failing for run pod, so the requirement was to have the collector name print (as below) in the error logs. See story #[109476](https://app.shortcut.com/replicated/story/109476/troubleshoot-print-collector-name-when-a-collector-fails)

Feature: Print runPod collector name in failed error logs

---

host/default.yaml

since runPod does not exist in host collector and we have run cat resolv.conf, it should be deleted.
https://github.com/replicatedhq/troubleshoot-specs/blob/5abc9eb87437e5afe29315eec968b28359cabd3c/host/default.yaml#L151 existed

fix(spec): remove non-exists host collector in default spec

---

scripts/tcpdump.sh

automate tcpdump given a pod name and namespace at the pod interface, vxlan bridge, and host primary.  Auto-switches for calico and flannel.

automate a tcpdump process

---

host/default.yaml

The collector adds up to 2mins to the collection process. Ideally, this add about 10 more seconds
If `fio` takes 2mins to do its thing, the process gets interrupted by `support-bundle` process

chore: Enable filesystem performance collector/analyser

---

in-cluster/default.yaml

Story details: https://app.shortcut.com/replicated/story/117738

feat: [sc-117738] detect "plugin/forward: no nameservers found" from support bundles

---

host/default.yaml

Collecting all k8s API server audit logs tend to generate large support bundles where audit logs account for `1GB` in size.  Not the entire audit history is always needed. This make it not ideal sending large bundles which need to be sent by customers to vendors, and then to Replicated.

chore: Only collect the latest k8s-audit API server log

---

host/default.yaml

Ensure Microsoft Defender Antivirus security tool is detected by the support bundle analysis.

chore: add Microsoft Defender Antivirus to the list of security tools

---

host/default.yaml
host/security-tools-preflights.yaml

* **Addition of `systemPackages` collector**: Introduced a new collector to identify specific security-related packages installed on `rhel` systems, such as `sdcss-kmod`, `sdcss`, and `sdcss-scripts`. [[1]](diffhunk://#diff-3fd0544bc822b0283dafcd0a7947e2a6fc35db9512cddc531280cd8fca6ed4b5R458-R463) [[2]](diffhunk://#diff-0ce4838bd81fb28acf149e02e17b76c561c82133410f672791ba677c1afe2adeR1-R39)
* **Refined regex for detecting running processes**: Updated the regex pattern in the `textAnalyze` analyzer to include `mdatp` for detecting running antivirus and network security tools. [[1]](diffhunk://#diff-3fd0544bc822b0283dafcd0a7947e2a6fc35db9512cddc531280cd8fca6ed4b5L834-R840) [[2]](diffhunk://#diff-0ce4838bd81fb28acf149e02e17b76c561c82133410f672791ba677c1afe2adeR1-R39)
* **System package …

feat: add security tools host preflight

---

host/security-tools-preflights.yaml

Add ubuntu packages to security-tools-preflights in tools host preflights

chore: add ubuntu packages to security-tools-preflights

---

host/default.yaml

Collect output of `ip -s -s address`, `lspci -vvv -D` and `ethtool -(a|g|k|c|i) <interface>`
Example output
```
ip -s -s address | grep eth1: -A20
5: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast state UP group default qlen 1000
link/ether 18:7b:b3:1e:04:60 brd ff:ff:ff:ff:ff:ff
inet 10.0.0.161/24 metric 100 brd 10.0.0.255 scope global dynamic eth1
valid_lft 41901sec preferred_lft 41901sec
inet6 fe80::1a7b:b3ff:fe1e:460/64 scope link
valid_lft forever preferred_lft forever
RX:  bytes packets errors dropped  missed   mcast
1371687222  171289      0       0       0       0
RX errors:  length    crc   frame    fifo overrun
0      0       0       0       0
TX:  bytes packets errors dropped carrier collsns
7715477  100950      0       0       0       0
TX errors: aborted …
```

chore: collect network interface statistics

---

host/infra-management-tools.yaml
host/security-tools-preflights.yaml
host/storage-checks.yaml
in-cluster/check-pod-limits.yaml

- Add a preflight spec that detects running infrastructure management tools in a VM. This spec is meant to warn users if any of the management tools are found so users can ensure the tools are configured not to interferer with configurations made for Embedded Cluster
- Add a storage check host preflight that uses environment variables to as template variables
- Add in-cluster preflight to check pod limits

feat: additional preflight checks
